settings:
  username: M4nzel
  max_lines: 5
  readme_file: ./README.md

  # Si quiere ver pushes, NO los deshabilite.
  # Si algo le rompe por Issues/PR, puede deshabilitarlos aqu√≠.
  # disabled_events:
  #   - issues
  #   - pull_request
